# Generated by Django 4.2.4 on 2023-11-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=700)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("active", models.BooleanField()),
                ("approved", models.BooleanField()),
                ("bundle", models.CharField(default="E-Way Bundle", max_length=200)),
            ],
        ),
    ]
