# Generated by Django 4.2.4 on 2023-11-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hooshunt", "0002_clue_point_value_usercluescore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clue",
            name="active",
        ),
        migrations.AddField(
            model_name="usercluescore",
            name="solved",
            field=models.BooleanField(default=False),
        ),
    ]
