# Generated by Django 4.2.4 on 2023-11-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hooshunt", "0002_clue_hints"),
        ("hooshunt", "0003_remove_clue_active_usercluescore_solved"),
    ]

    operations = []
